spring:
  ai:
    openai:
      api-key: xxxxxx
      chat:
        base-url: https://ark.cn-beijing.volces.com/api/v3
        completions-path: /chat/completions
        options:
          model: ep-20250117161524-4knd5