server:
  port: 8060
spring:
  application:
    name: mcp-summary
  profiles:
    active: deepseek
  ai:
    mcp:
      server:
        enabled: true
        name: mcp-summary
        version: 1.0.0
        authentication:
          enabled: true
          type: none  # 设置为 none 表示不需要认证
        streaming:
          enabled: false
      client:
        authentication:
          enabled: true
          type: none  # 设置为 none 表示不需要认证
        streaming:
          enabled: false
        retry:
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2.0
          max-interval: 10000
    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
          username: "root"
          password: "milvus"
        databaseName: "default"
        collectionName: "vector_store"
        embeddingDimension: 1536
        indexType: IVF_FLAT
        metricType: COSINE
