server:
  port: 8060

#spring.ai.openai.api-key=sk-7ca472e997e449fe9e57e27c52526705
#spring.ai.openai.chat.base-url=https://api.deepseek.com
#spring.ai.openai.chat.completions-path=/v1/chat/completions
#spring.ai.openai.chat.options.model=deepseek-chat
spring:
  application:
    name: mcp-sample
  profiles:
    active: doubao
  ai:
    mcp:
      server:
        enabled: true
        name: mcp-sample
        version: 1.0.0
        authentication:
          enabled: true
          type: none  # 设置为 none 表示不需要认证
        streaming:
          enabled: false
      client:
        authentication:
          enabled: true
          type: none  # 设置为 none 表示不需要认证
        streaming:
          enabled: false
        retry:
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2.0
          max-interval: 10000
